apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: urban-mobility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: ghcr.io/motofix/analytics-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mobility-platform-config
          env:
            - name: HTTP_ADDR
              value: ":8080"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: urban-mobility
spec:
  selector:
    app: analytics-service
  ports:
    - port: 80
      targetPort: 8080

