apiVersion: v1
kind: ConfigMap
metadata:
  name: mobility-platform-config
  namespace: urban-mobility
data:
  KAFKA_BROKERS: "redpanda.redpanda.svc.cluster.local:9092"
  REDIS_ADDR: "redis.redis.svc.cluster.local:6379"
  POSTGRES_URL: "postgres://mobility:mobility@postgres.postgres.svc.cluster.local:5432/mobility?sslmode=disable"

